name: get_it_done_x
description: Todo List using GetX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.1.1
  equatable: ^2.0.5
  dotted_border: ^2.0.0+3
  percent_indicator: ^4.2.3
  fluttertoast: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

